package com.raphaowl.covidmap.enumerator;

import lombok.Getter;

@Getter
public enum CountryEnum {

    CHINA("China"),
    ITALIA("Itália"),
    ESTADOS_UNIDOS("Estados Unidos"),
    ESPANHA("Espanha"),
    ALEMANHA("Alemanha"),
    IRA("Irã"),
    FRANCA("França"),
    COREIA_DO_SUL("Coreia do Sul"),
    SUICA("Suíça"),
    REINO_UNIDO("Reino Unido"),
    PAISES_BAIXOS("Países Baixos"),
    BELGICA("Bélgica"),
    AUSTRIA("Austria"),
    NORUEGA("Noruega"),
    SUECIA("Suécia"),
    PORTUGAL("Portugal"),
    DINAMARCA("Dinamarca"),
    CANADA("Canadá"),
    AUSTRALIA("Austrália"),
    MALASIA("Malásia"),
    BRASIL("Brasil"),
    TCHEQUIA("Tchéquia"),
    JAPAO("Japão"),
    TURQUIA("Turquia"),
    ISRAEL("Israel"),
    LUXEMBURGO("Luxemburgo"),
    EQUADOR("Equador"),
    IRLANDA("Irlanda"),
    PAQUISTAO("Paquistão"),
    DIAMOND_PRINCESS("Diamond Princess"),
    CHILE("Chile"),
    FINLANDIA("Finlândia"),
    TAILANDIA("Tailândia"),
    ISLANDIA("Islândia"),
    POLONIA("Polônia"),
    GRECIA("Grécia"),
    INDONESIA("Indonésia"),
    ARABIA_SAUDITA("Arábia Saudita"),
    CATAR("Catar"),
    SINGAPURA("Singapura"),
    ROMENIA("Romênia"),
    ESLOVENIA("Eslovênia"),
    FILIPINAS("Filipinas"),
    RUSSIA("Rússia"),
    PERU("Peru"),
    INDIA("India"),
    BAHREIN("Bahrein"),
    ESTONIA("Estônia"),
    RAE_DE_HONG_KONG("RAE de Hong Kong"),
    EGITO("Egito"),
    CROACIA("Croácia"),
    MEXICO("México"),
    LIBANO("Líbano"),
    PANAMA("Panamá"),
    AFRICA_DO_SUL("Africa do Sul"),
    IRAQUE("Iraque"),
    COLOMBIA("Colômbia"),
    ARGENTINA("Argentina"),
    REPUBLICA_DOMINICANA("República Dominicana"),
    ARMENIA("Armênia"),
    KUWAIT("Kuwait"),
    SERVIA("Sérvia"),
    BULGARIA("Bulgária"),
    ESLOVAQUIA("Eslováquia"),
    SAN_MARINO("San Marino"),
    TAIWAN("Taiwan"),
    EMIRADOS_ARABES_UNIDOS("Emirados Arabes Unidos"),
    ARGELIA("Argélia"),
    LETONIA("Letônia"),
    URUGUAI("Uruguai"),
    HUNGRIA("Hungria"),
    COSTA_RICA("Costa Rica"),
    MACEDONIA_DO_NORTE("Macedônia do Norte"),
    VIETNA("Vietnã"),
    ANDORRA("Andorra"),
    MARROCOS("Marrocos"),
    LITUANIA("Lituânia"),
    JORDANIA("Jordânia"),
    BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina"),
    MALTA("Malta"),
    ALBANIA("Albânia"),
    BRUNEI("Brunei"),
    CAMBOJA("Camboja"),
    SRI_LANKA("Sri Lanka"),
    MOLDOVA("Moldova"),
    BELARUS("Belarus"),
    BURQUINA_FASO("Burquina Faso"),
    CHIPRE("Chipre"),
    TUNISIA("Tunísia"),
    VENEZUELA("Venezuela"),
    NOVA_ZELANDIA("Nova Zelândia"),
    AZERBAIJAO("Azerbaijão"),
    AUTORIDADE_PALESTINA("Autoridade Palestina"),
    CAZAQUISTAO("Cazaquistão"),
    SENEGAL("Senegal"),
    OMA("Omã"),
    GEORGIA("Geórgia"),
    UCRANIA("Ucrânia"),
    LIECHTENSTEIN("Liechtenstein"),
    UZBEQUISTAO("Uzbequistão"),
    CAMAROES("Camarões"),
    AFEGANISTAO("Afeganistão"),
    KOSOVO("Kosovo"),
    NIGERIA("Nigéria"),
    BANGLADESH("Bangladesh"),
    HONDURAS("Honduras"),
    CONGO("Congo (RDC)"),
    PARAGUAI("Paraguai"),
    CUBA("Cuba"),
    GANA("Gana"),
    BOLIVIA("Bolívia"),
    GUERNSEY("Guernsey"),
    JAMAICA("Jamaica"),
    RAE_DE_MACAU("RAE de Macau"),
    MAURICIO("Maurício"),
    GUATEMALA("Guatemala"),
    COTE_DIVOIRE("Côte d’Ivoire"),
    RUANDA("Ruanda"),
    MONTENEGRO("Montenegro"),
    TOGO("Togo"),
    JERSEY("Jersey"),
    QUIRGUISTAO("Quirguistão"),
    MALDIVAS("Maldivas"),
    TANZANIA("Tanzânia"),
    MONACO("Mônaco"),
    ETIOPIA("Etiópia"),
    MONGOLIA("Mongólia"),
    TRINIDAD_E_TOBAGO("Trinidad e Tobago"),
    QUENIA("Quênia"),
    SEICHELES("Seicheles"),
    GUINE_EQUATORIAL("Guiné Equatorial"),
    BARBADOS("Barbados"),
    ISLE_OF_MAN("Isle of Man"),
    SURINAME("Suriname"),
    BAHAMAS("Bahamas"),
    ESSUATINI("Essuatíni"),
    GABAO("Gabão"),
    GUIANA("Guiana"),
    CAPE_VERDE("Cape Verde"),
    REPUBLICA_CENTRO_AFRICANA("República Centro-Africana"),
    EL_SALVADOR("El Salvador"),
    MADAGASCAR("Madagascar"),
    LIBERIA("Libéria"),
    NAMIBIA("Namíbia"),
    ZAMBIA("Zâmbia"),
    ZIMBABUE("Zimbábue"),
    ANGOLA("Angola"),
    BENIN("Benin"),
    BUTAO("Butão"),
    FIJI("Fiji"),
    GUINE("Guiné"),
    HAITI("Haiti"),
    MAURITANIA("Mauritânia"),
    NICARAGUA("Nicarágua"),
    NIGER("Níger"),
    SANTA_LUCIA("Santa Lúcia"),
    SUDAO("Sudão"),
    ANTIGUA_E_BARBUDA("Antígua e Barbuda"),
    CHADE("Chade"),
    DJIBUTI("Djibuti"),
    ERITREIA("Eritreia"),
    MOCAMBIQUE("Moçambique"),
    NEPAL("Nepal"),
    PAPUA_NOVA_GUINE("Papua-Nova Guiné"),
    SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
    SOMALIA("Somália"),
    UGANDA("Uganda"),
    CIDADE_DO_VATICANO("Cidade do Vaticano");

    private String name;

    CountryEnum(String name) {
        this.name = name;
    }
}
